name: Differentiation Benchmarks
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Differentiation benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["6.0.3"]
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Verify Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install "pandas==2.2.3"
      - name: Verify package installation
        run: python -c "import pandas as pd; print(pd.__version__)"
      - run: apt-get -q update && apt-get install -y libjemalloc-dev
      - name: Run benchmarks
        run: cd RuntimePerformanceTests && swift package --allow-writing-to-package-directory benchmark --format influx --path benchmark-raw-output
      - name: Process benchmarks
        run: cd RuntimePerformanceTests && ./parse-benchmarks
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: package-benchmark
          tool: 'customBiggerIsBetter'
          output-file-path: RuntimePerformanceTests/bench-mean-results.json
          benchmark-data-dir-path: "RuntimePerformanceTests/results"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          alert-comment-cc-users: '@JaapWijnen'
