
name: Runtime Crash Tests Pipeline

on: [pull_request]

jobs:
  build:
    name: RuntimeCrash Tests Swift ${{ matrix.swift }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["6.0", "6.0.1", "6.0.2"]
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - run: (cd RuntimeCrashTests && ./run-runtime-crash-tests.sh)
