
name: Runtime Validation Tests Pipeline

on: [pull_request]

jobs:
  build:
    name: Swift ${{ matrix.swift }} Linux
    strategy:
      matrix:
        swift: ["6.0", "6.0.1", "6.0.2"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Build RuntimeValidationTests
        run: swift build --package-path RuntimeValidationTests
      - name: Test RuntimeValidationTests
        run: swift test --package-path RuntimeValidationTests

