
name: tests

on:
  pull_request:
  push:
    branches:
     - main

jobs:
  compiletime-crash-tests:
    name: Compiletime Crash Tests Swift ${{ matrix.swift }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["6.0.3"]
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Verify Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install "pandas~=2.2" "influxdb_client~=1.48"
      - name: Verify package installation
        run: python -c "import pandas as pd; print(pd.__version__); import influxdb_client; print(influxdb_client.__version__)"
      - run: (cd CompiletimeCrashTests && ./run-compiletime-crash-tests.sh)
      - name: Upload to Influx
        if: ${{ github.event_name == 'push' }}
        env:
          INFLUX_BUCKET_NAME: ${{ secrets.InfluxBucketName }}
          INFLUX_UPLOAD_TOKEN: ${{ secrets.InfluxUploadToken }}
          INFLUX_ORG_NAME: ${{ secrets.InfluxOrgName }}
          INFLUX_URL: ${{ secrets.InfluxURL }}
        run: cd RuntimePerformanceTests && python benchmark-upload.py

  runtime-crash-tests:
    name: Runtime Crash Tests Swift ${{ matrix.swift }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["6.0.3"]
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - run: (cd RuntimeCrashTests && ./run-runtime-crash-tests.sh)

  runtime-validation-tests:
    name: Runtime Validation Tests Swift ${{ matrix.swift }}
    strategy:
      matrix:
        swift: ["6.0.3"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Build RuntimeValidationTests
        run: swift build --package-path RuntimeValidationTests
      - name: Test RuntimeValidationTests
        run: swift test --package-path RuntimeValidationTests

